name: ipython-notebook
dependencies:
  - notebook
  - ipywidgets
  - requests
  # get dependencies for pgcontents
  - certifi
  - click
  - mako
  - psycopg2
  - six
  - sqlalchemy
  - nose
  - pip:
    - numpy
    - scipy
    - pydicom
    - scikit-image
    - matplotlib
    - git+git://github.com/pl31/pgcontents.git
    - git+git://github.com/Theano/Theano.git
    - git+git://github.com/fchollet/keras.git
